# Generated by Django 5.1.5 on 2025-04-21 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta de crédito'), ('yape', 'Yape'), ('plin', 'Plin')], max_length=20)),
                ('tipo_comprobante', models.CharField(choices=[('boleta', 'Boleta'), ('factura', 'Factura')], max_length=20)),
                ('tipo_documento', models.CharField(choices=[('dni', 'DNI'), ('ruc', 'RUC'), ('ce', 'Carné de extranjería'), ('pasaporte', 'Pasaporte')], default='dni', max_length=20)),
                ('nombres_cliente', models.CharField(max_length=100)),
                ('apellidos_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('documento_cliente', models.CharField(max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('anulada', models.BooleanField(default=False)),
                ('vendedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.venta')),
            ],
        ),
    ]
