# Generated by Django 5.1.5 on 2025-05-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_caja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='fecha_apertura',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='caja',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
