# Generated by Django 5.2.1 on 2025-05-16 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_venta_total'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprobaciones_cierre', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caja',
            name='cierre_aprobado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caja',
            name='cierre_solicitado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caja',
            name='descripcion_cierre',
            field=models.TextField(blank=True),
        ),
    ]
