# Generated by Django 5.2.1 on 2025-05-23 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_solicitudanulacionventa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudanulacionventa',
            old_name='fecha_aprobacion',
            new_name='fecha_revision',
        ),
        migrations.RenameField(
            model_name='solicitudanulacionventa',
            old_name='solicitado_por',
            new_name='usuario_solicitante',
        ),
        migrations.RemoveField(
            model_name='solicitudanulacionventa',
            name='aprobado_por',
        ),
        migrations.RemoveField(
            model_name='solicitudanulacionventa',
            name='estado',
        ),
        migrations.AddField(
            model_name='solicitudanulacionventa',
            name='aprobada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudanulacionventa',
            name='revisada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anulaciones_revisadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitudanulacionventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.venta'),
        ),
    ]
