# Generated by Django 5.2.1 on 2025-05-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_rename_fecha_aprobacion_solicitudanulacionventa_fecha_revision_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudanulacionventa',
            name='aprobada',
        ),
        migrations.AddField(
            model_name='solicitudanulacionventa',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20),
        ),
    ]
