# Generated by Django 5.2.1 on 2025-05-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_remove_solicitudanulacionventa_aprobada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='razon_social',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
