# Generated by Django 5.2.1 on 2025-05-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_venta_razon_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='razon_social',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
