# Generated by Django 5.2.1 on 2025-05-30 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_alter_venta_razon_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientocaja',
            name='caja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='ventas.caja'),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='tipo',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso'), ('venta', 'Venta'), ('devolucion', 'Devolución')], max_length=20),
        ),
    ]
