# Generated by Django 5.2.1 on 2025-05-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0013_alter_movimientocaja_caja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='nombre_cliente',
            field=models.TextField(blank=True),
        ),
    ]
