# Generated by Django 5.2.1 on 2025-05-30 20:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0014_movimientocaja_nombre_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='PagoCliente',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='VueltoCliente',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
