# Generated by Django 5.2.1 on 2025-05-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0015_movimientocaja_pagocliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='nombre_empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
