# Generated by Django 5.2.1 on 2025-06-06 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0017_venta_card_number_venta_card_token_venta_expiry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='card_token',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='transaction_id',
        ),
    ]
