# Generated by Django 5.2.1 on 2025-07-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0019_solicitudaperturacaja'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudaperturacaja',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudaperturacaja',
            name='estado',
            field=models.CharField(max_length=20),
        ),
    ]
