# Generated by Django 5.1.5 on 2025-04-24 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.IntegerField(default=5),
        ),
    ]
