# Generated by Django 5.1.5 on 2025-04-24 23:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_producto_stock_minimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_ingreso',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
