# Generated by Django 5.2.1 on 2025-05-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_producto_fecha_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='talla',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
